CREATE DATABASE CONSULTORA COLLATE = "utf8_spanish_ci";

CREATE TABLE USUARIOS (ID_USUARIO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, NOMBRE VARCHAR(12), APELLIDOS VARCHAR(25), EMAIL VARCHAR(140), FECHA_NACIMIENTO DATETIME);

CREATE TABLE OCUPACION (ID_OCUPACION INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, NOMBRE VARCHAR(100), FK_USUARIO INTEGER);

CREATE TABLE USUARIO_OCUPACION (ID_UO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, FK_USUARIO INTEGER, FK_OCUPACION INTEGER);

CREATE TABLE INFORMES (ID_INFORME INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, TITULO VARCHAR(120), SUBTITULO VARCHAR(140), MINUTA VARCHAR(100), FECHA_PUBLICACION DATETIME, FK_USUARIO INTEGER, FK_TEMA INTEGER);

CREATE TABLE TEMAS (ID_TEMA INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, NOMBRE VARCHAR(120));

CREATE TABLE COMENTARIOS (ID_COMENTARIO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, COMENTARIO VARCHAR(200), FK_INFORME INTEGER, FK_USUARIO INTEGER);

CREATE TABLE ARCHIVOS (ID_ARCHIVO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, ARCHIVOS VARCHAR (250), FK_INFORME INTEGER);



ALTER TABLE INFORMES ADD FOREIGN KEY (FK_USUARIO) REFERENCES USUARIOS(ID_USUARIO);
ALTER TABLE INFORMES ADD FOREIGN KEY (FK_TEMA) REFERENCES TEMAS(ID_TEMA);
ALTER TABLE COMENTARIOS ADD FOREIGN KEY (FK_INFORME) REFERENCES INFORMES(ID_INFORME);
ALTER TABLE COMENTARIOS ADD FOREIGN KEY (FK_USUARIO) REFERENCES USUARIOS(ID_USUARIO);
ALTER TABLE ARCHIVOS ADD FOREIGN KEY (FK_INFORME) REFERENCES INFORMES(ID_INFORME);
ALTER TABLE OCUPACION ADD FOREIGN KEY (FK_USUARIO) REFERENCES USUARIOS(ID_USUARIO);
ALTER TABLE USUARIO_OCUPACION ADD FOREIGN KEY (FK_USUARIO) REFERENCES USUARIOS(ID_USUARIO);
ALTER TABLE USUARIO_OCUPACION ADD FOREIGN KEY (FK_OCUPACION) REFERENCES OCUPACION(ID_OCUPACION);



INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Carlos', 'Villareal', 'CVillareal@yahoo.com', '1975-4-15 13:00:00');
INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Lucas', 'Martinez', 'Martinez.Lucas@hotmail.com', '1992-8-20 21:45:00');
INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Martin', 'Perez', 'martinperez1989@gmail.com', '1989-5-02 15:06:55');
INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Juan', 'Hernandez', 'JuanHernandez2@gmail.com', '1983-3-06 05:23:55');
INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Hernesto', 'Lugerezzi', 'Lug.Hernesto@yahoo.com', '1965-6-15 23:08:45');
INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Juan', 'Perez', 'JuanP1986@gmail.com',  '1986-06-25 11:16:52');
INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Federico', 'Guemez', 'FedeGuemez@hotmail.com', '1993-4-20 09:07:15');
INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Lucia', 'Fiola', 'LucyFiola@gmail.com', '1970-7-22 20:08:59');
INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Lucas', 'Diaz', 'DiazLucas1987@yahoo.com', '1987-5-25 18:14:23');
INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Tomas', 'Almagro', 'TA1976@gmail.com', '1976-6-15 03:18:39');
INSERT INTO `USUARIOS`(`NOMBRE`, `APELLIDOS`, `EMAIL`, `FECHA_NACIMIENTO`)
VALUES('Tomas', 'Uriburu', 'TUriburu@gmail.com', '1965-6-15 06:22:59');



INSERT INTO `OCUPACION`(`NOMBRE`) VALUES ('Electrisista');
INSERT INTO `OCUPACION`(`NOMBRE`) VALUES ('Abogado');
INSERT INTO `OCUPACION`(`NOMBRE`) VALUES ('Contador');
INSERT INTO `OCUPACION`(`NOMBRE`) VALUES ('Analista en Sistemas');
INSERT INTO `OCUPACION`(`NOMBRE`) VALUES ('Manejo de contratacion');
INSERT INTO `OCUPACION`(`NOMBRE`) VALUES ('Escribano');
INSERT INTO `OCUPACION`(`NOMBRE`) VALUES ('Pintor');
INSERT INTO `OCUPACION`(`NOMBRE`) VALUES ('Limpieza');
INSERT INTO `OCUPACION`(`NOMBRE`) VALUES ('Diseño Grafico');
INSERT INTO `OCUPACION`(`NOMBRE`) VALUES ('Seguridad');



INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(1, 1);
INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(2, 2);
INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(3, 3);
INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(4, 4);
INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(5, 5);
INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(6, 6);
INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(7, 7);
INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(8, 8);
INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(9, 9);
INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(10, 10);
INSERT INTO `USUARIO_OCUPACION`(`FK_USUARIO`, `FK_OCUPACION`) VALUES(11, 10);



INSERT INTO `TEMAS`(`NOMBRE`) VALUES('Reparaciones');
INSERT INTO `TEMAS`(`NOMBRE`) VALUES('Legalidad');
INSERT INTO `TEMAS`(`NOMBRE`) VALUES('Impuestos');
INSERT INTO `TEMAS`(`NOMBRE`) VALUES('Desarrollo Web');
INSERT INTO `TEMAS`(`NOMBRE`) VALUES('Contratos');
INSERT INTO `TEMAS`(`NOMBRE`) VALUES('Escrituras');
INSERT INTO `TEMAS`(`NOMBRE`) VALUES('Refaccion');
INSERT INTO `TEMAS`(`NOMBRE`) VALUES('Higiene');
INSERT INTO `TEMAS`(`NOMBRE`) VALUES('Disenio Web');
INSERT INTO `TEMAS`(`NOMBRE`) VALUES('Seguridad');



INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Reparacion cableado', 'Desprecarizacion de la gestion electrica de la empresa', '2018-7-05 15:00:00', '11500 pesos', 1, 1);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Cambio de tubos', 'Cambio de tubos de luz vencidos en la empresa', '2018-7-09 15:00:00', '11500 pesos', 1, 1);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Legales', 'Resolver asuntos legales de la empresa', '2020-9-14 15:00:00', '64500 pesos', 2, 2);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Area Contable', 'Paga de impuestos', '2020-9-20 15:00:00', '80000 pesos', 3, 3);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Desarrollo Web', 'Desarrollo estructural de la web de la empresa', '2015-7-25 15:00:00', '71600 pesos', 4, 4);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Manejo de contratacion', 'Analisis de posibles candidatos para la empresa', '2020-1-09 15:00:00', '45700 pesos', 5, 5);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Nueva sede', 'Validar escrituras de la nueva sede de la empresa', '2013-6-15 15:00:00', '30520 pesos', 6, 6);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Senia', 'Ademas del contrato, debemos pagar la senia del alquiler de la sede nueva.', '2013-6-15 15:00:00', '176903 pesos', 6, 6);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Cambio ambiente', 'Reboque y pintado de paredes de la empresa', '2014-2-02 15:00:00', '17500 pesos', 7, 7);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Limpieza', 'Mantenimiento e higiene de la empresa', '2020-11-30 15:00:00', '15000 pesos', 8, 8);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Disenio web', 'Calidad estetica de la pagina de la empresa', '2015-7-25 15:00:00', '35700 pesos', 9, 9);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Portero', 'Servicio de seguridad para la empresa', '2019-5-14 15:00:00', '25300 pesos', 10, 10);
INSERT INTO `INFORMES`(`TITULO`, `SUBTITULO`, `FECHA_PUBLICACION`, `MINUTA`, `FK_USUARIO`, `FK_TEMA`)
VALUES('Portero', 'Servicio de seguridad para la empresa', '2019-5-14 15:00:00', '29300 pesos', 11, 10);



INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('El duenio anterior habia dejado cables desinstalados colgando, arreglar.', 1, 1);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Basicamente necesitamos que corroboren que todos los trabajadores estan en blanco.', 3, 2);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Es importante pagar los impuestos al dia, para evitar deudas monstruosas.', 4, 3);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Vamos a actualizar la imagen de la empreza, empezemos la estructura de la web.', 5, 4);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Es dificil determinar candidatos para un trabajo.', 6, 5);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('2013 anio de mudanza de la sede.', 7, 6);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Nos mudamos a Moldes 2064.', 7, 6);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Las pinturas 6 y 15 estan...bien.', 9, 7);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Las 2 y 7 me gustan mas.', 9, 7);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Aunque mi asesor de imagen me dice que la 5 y 12 pueden ser mas calidas.', 9, 7);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Mujer muy comprometida con el aseo del edificio.', 10, 8);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Desarrollar una imagen de web moderna.', 11, 9);
INSERT INTO `COMENTARIOS`(`COMENTARIO`, `FK_INFORME`, `FK_USUARIO`)
VALUES('Hombre forzudo de ser posible, queremos buena seguridad aca.', 13, 11);



INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('cablesColgando.jpg', 1);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('presentacionDocumentos.pdf', 2);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('relatoValores.mp3', 3);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('esquemaWeb.pdf', 4);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('informeContratos.mp3', 5);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('Contrato.pdf', 6);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('pinturas1.jpg', 7);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('pinturas2.gif', 7);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('imagenEmpleada.jpg', 8);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('webFinal1.jpg', 9);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('webFinal2.jpg', 9);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('webFinal3.jpg', 9);
INSERT INTO `ARCHIVOS`(`ARCHIVOS`, `FK_INFORME`) VALUES ('imagenEmpleado.jpg', 10);
