CREATE DATABASE EJERCICIO3
COLLATE=`utf8_spanish_ci`;

CREATE TABLE LIBROS(ID_LIBRO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, AUTOR VARCHAR(140), TITULO VARCHAR(140), SUBTITULO VARCHAR(140), EDICION VARCHAR(140), LUGAR_EDICION VARCHAR(140), EDITORIAL VARCHAR(140), ANIO_EDICION SMALLINT(10), NUMERO_PAGINAS INTEGER(10), LOCALIZACION INTEGER);

CREATE TABLE ESTANTERIAS(ID_ESTANTERIA INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, SECCION VARCHAR(140));



ALTER TABLE LIBROS
ADD FOREIGN KEY (LOCALIZACION) REFERENCES ESTANTERIAS(ID_ESTANTERIA);






INSERT INTO `ESTANTERIAS`(`SECCION`)
VALUES('Ciencia Ficción');

INSERT INTO `LIBROS`(`AUTOR`, `TITULO`, `SUBTITULO`, `EDICION`, `LUGAR_EDICION`, `EDITORIAL`, `ANIO_EDICION`, `NUMERO_PAGINAS`, `LOCALIZACION`)
VALUES('Claudia Gray', 'Estrellas Perdidas', 'Rumbo a Star Wars: El Despertar de la Fuerza', '', 'Nueva York, Estados Unidos', 'Editorial Planeta', 2015, 480, 1), ('Chuck Wendig', 'Consecuencias', 'La guerra no ha terminado', 'Del Rey', 'New Hope, Pensilvania, Estados Unidos', 'Editorial Planeta', 2015, 455, 1);
