CREATE DATABASE EJERCICIO2
COLLATE=`utf8_spanish_ci`;

CREATE TABLE PACIENTES (ID_PACIENTE INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, NOMBRE VARCHAR(20), APELLIDOS VARCHAR(45), DIRECCION VARCHAR(140), LOCALIDAD VARCHAR(80), PROVINCIA VARCHAR(140), CODIGO_POSTAL VARCHAR(16), TELEFONO VARCHAR(20), FECHA_NACIMIENTO VARCHAR(140));

CREATE TABLE MEDICOS (ID_MEDICO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, NOMBRE VARCHAR(20), APELLIDOS VARCHAR(45), TELEFONO VARCHAR(20), ESPECIALIDAD VARCHAR(140));

CREATE TABLE INGRESOS (ID_INGRESO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,ID_PACIENTE INTEGER, ID_MEDICO INTEGER, FECHAHORA TIMESTAMP NOT NULL, NUMERO_HABITACION INTEGER(6), CAMA INTEGER(6));



ALTER TABLE INGRESOS
ADD FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO);

ALTER TABLE INGRESOS
ADD FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE);



INSERT INTO `PACIENTES` (`NOMBRE`, `APELLIDOS`, `DIRECCION`, `LOCALIDAD`, `PROVINCIA`, `CODIGO_POSTAL`, `TELEFONO`, `FECHA_NACIMIENTO`)
VALUES ('Carlos', 'Fernandez', 'Avenida Directorio 5386', 'Mataderos', 'Buenos Aires', 'C1440ASS', 5191148560376, '17 de Octubre de 1978');

INSERT INTO `MEDICOS` (`NOMBRE`, `APELLIDOS`, `TELEFONO`, `ESPECIALIDAD`)
VALUES ('Lucia', 'Gomez', '5491149249297', 'Cirujano Plastico'); 

INSERT INTO `INGRESOS` (`ID_PACIENTE`, `ID_MEDICO`, `NUMERO_HABITACION`, `CAMA`)
VALUES (1, 1, 47, 1);
